### ISSUE TITLE
TypeError: move(self, int, int): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by hubismal** [Falano/kritaSpritesheetManager#16]
Get this error when trying to export anything in krita to a standard spritesheet on Krita 4.4.8.
```
TypeError
Python 3.10.1: /usr/bin/python3
Sun Dec 19 18:20:52 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/hub/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py in confirmButton(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
  411         else:
  412             # important: we reset spritesheetexporter's spritesExportDir
  413             self.exp.spritesExportDir = self.exp.defaultPath
  414         self.exp.export()
  415         self.mainDialog.hide()
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.exp = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.exp.export = <bound method SpritesheetExporter.export of <spr....spritesheetexporter.SpritesheetExporter object>>

 /home/hub/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in export(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, debugging=False)
  349                 layer = sheet.createFileLayer(img, img, "ImageToSize")
  350                 root_node.addChildNode(layer, None)
  351                 self.positionLayer(
  352                     layer=layer,
  353                     imgNum=(((frameIDNum - invisibleLayersNum)- self.start)/self.step),
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.positionLayer = <bound method SpritesheetExporter.positionLayer ....spritesheetexporter.SpritesheetExporter object>>
layer = <PyKrita.krita.FileLayer object>
imgNum undefined
frameIDNum = -1
invisibleLayersNum = 0
self.start = -1
self.step = 1
width = 32
height = 32

 /home/hub/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in positionLayer(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, layer=<PyKrita.krita.FileLayer object>, imgNum=0.0, width=32, height=32)
   43     def positionLayer(self, layer, imgNum, width, height):
   44         if self.isDirectionHorizontal:
   45             layer.move((imgNum % self.columns) * width,
   46                        (int(imgNum/self.columns)) * height)
   47         else:
layer = <PyKrita.krita.FileLayer object>
layer.move = <built-in method move of FileLayer object>
imgNum = 0.0
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.columns = 1
width = 32
builtinint = <class 'int'>
height = 32
TypeError: move(self, int, int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("move(self, int, int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/hub/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py", line 414, in confirmButton
    self.exp.export()
  File "/home/hub/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 351, in export
    self.positionLayer(
  File "/home/hub/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 45, in positionLayer
    layer.move((imgNum % self.columns) * width,
TypeError: move(self, int, int): argument 1 has unexpected type 'float'
```

**Comment by QbieShay** [comment]
I have a (dirty) fix for this in https://github.com/Falano/kritaSpritesheetManager/pull/17. not the best solution but works?

**Comment by eh-jogos** [comment]
I'm getting the same error, thanks for the alternative fix

**Comment by Falano** [comment]
thanks for the fix! I merged it.
