### ISSUE TITLE
Possible to add 'trim' option?

### ISSUE THREAD

**Issue by HiccupsVoice** [Falano/kritaSpritesheetManager#6]
Hi Falano,

I want to thank you, first of all, for taking on this project and putting this script together. I have had no issues so far with getting the script do what it is designed to do. Props.

I have one suggestion, hopefully relatively easy. Could there be an option to create 'compact' sprite sheets? I did a test run with a sloppy bouncey ball animation on a transparent background (below). All the X and Y space around the ball is retained in each frame. Could there be an autocrop implemented in the temp folder to trim empty pixels, so that each row in the sheet has a 'floor' that, e.g., a jumping character's toes remained in contact with, and so on?

In any case, this is a great script. They should really start including it in the main distro, but I'm glad to have found it.
-Hiccupsvoice

![Spritesheet_ballbounce_transparentBG](https://user-images.githubusercontent.com/54667839/63934756-b15e7580-ca21-11e9-8930-905245a9551e.png)

**Comment by Falano** [comment]
Hi!
Sorry for the late answer.
I'll think about it. If I have some time I might do it, but don't expect it soon.

**Comment by diegosarzi** [comment]
AttributeError
Python 3.7.3: /usr/bin/python3
Sun Apr  5 18:01:22 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/gnew/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py in confirmButton(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
  378         else:
  379             # important: we reset spritesheetexporter's spritesExportDir
  380             self.exp.spritesExportDir = self.exp.defaultPath
  381         self.exp.export()
  382         self.mainDialog.hide()
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.exp = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.exp.export = <bound method SpritesheetExporter.export of <spr....spritesheetexporter.SpritesheetExporter object>>

 /home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in export(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, debugging=False)
  153         # and if needed input default value
  154         if(self.end == self.defaultTime or self.start == self.defaultTime):
  155             self.setStartEndFrames()
  156         doc.setCurrentTime(self.start)
  157         if(debugging):
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.setStartEndFrames = <bound method SpritesheetExporter.setStartEndFra....spritesheetexporter.SpritesheetExporter object>>

 /home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in setStartEndFrames(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>)
   81         if self.end == self.defaultTime:
   82             for layer in layers:
   83                 self.checkLayerEnd(layer, doc)
   84         # get first frame of all visible layers
   85         if self.start == self.defaultTime:
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.checkLayerEnd = <bound method SpritesheetExporter.checkLayerEnd ....spritesheetexporter.SpritesheetExporter object>>
layer = <PyKrita.krita.Node object>
doc = <PyKrita.krita.Document object>

 /home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in checkLayerEnd(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, layer=<PyKrita.krita.Node object>, doc=<PyKrita.krita.Document object>)
   46         if layer.visible():
   47             if layer.animated():
   48                 frame = doc.fullClipRangeEndTime()
   49                 while not (layer.hasKeyframeAtTime(frame)
   50                     or frame < 0):
frame undefined
doc = <PyKrita.krita.Document object>
doc.fullClipRangeEndTime undefined
AttributeError: 'Document' object has no attribute 'fullClipRangeEndTime'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'Document' object has no attribute 'fullClipRangeEndTime'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py", line 381, in confirmButton
    self.exp.export()
  File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 155, in export
    self.setStartEndFrames()
  File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 83, in setStartEndFrames
    self.checkLayerEnd(layer, doc)
  File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 48, in checkLayerEnd
    frame = doc.fullClipRangeEndTime()
AttributeError: 'Document' object has no attribute 'fullClipRangeEndTime'

**Comment by Falano** [comment]
Hi,
could you please open a new issue for this, as it's unrelated to the trim option? I'll answer there so we don't bother the original poster any more.
